version: "3.9"
services:
  user-http:
    build:
      context: .
      dockerfile: Dockerfile.Http.User
    ports:
      - 3000:3000

  item-http:
    build:
      context: .
      dockerfile: Dockerfile.Http.Item
    ports:
      - 4000:4000

  item-grpc:
    build:
      context: .
      dockerfile: Dockerfile.Grpc.Item
    ports:
      - 4100:4100