// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: src/proto/item/item.proto

package stupid_inventory

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ItemService_FindOneItem_FullMethodName = "/ItemService/FindOneItem"
)

// ItemServiceClient is the client API for ItemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ItemServiceClient interface {
	FindOneItem(ctx context.Context, opts ...grpc.CallOption) (ItemService_FindOneItemClient, error)
}

type itemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewItemServiceClient(cc grpc.ClientConnInterface) ItemServiceClient {
	return &itemServiceClient{cc}
}

func (c *itemServiceClient) FindOneItem(ctx context.Context, opts ...grpc.CallOption) (ItemService_FindOneItemClient, error) {
	stream, err := c.cc.NewStream(ctx, &ItemService_ServiceDesc.Streams[0], ItemService_FindOneItem_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &itemServiceFindOneItemClient{stream}
	return x, nil
}

type ItemService_FindOneItemClient interface {
	Send(*ItemReq) error
	CloseAndRecv() (*ItemArr, error)
	grpc.ClientStream
}

type itemServiceFindOneItemClient struct {
	grpc.ClientStream
}

func (x *itemServiceFindOneItemClient) Send(m *ItemReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *itemServiceFindOneItemClient) CloseAndRecv() (*ItemArr, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ItemArr)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ItemServiceServer is the server API for ItemService service.
// All implementations must embed UnimplementedItemServiceServer
// for forward compatibility
type ItemServiceServer interface {
	FindOneItem(ItemService_FindOneItemServer) error
	mustEmbedUnimplementedItemServiceServer()
}

// UnimplementedItemServiceServer must be embedded to have forward compatible implementations.
type UnimplementedItemServiceServer struct {
}

func (UnimplementedItemServiceServer) FindOneItem(ItemService_FindOneItemServer) error {
	return status.Errorf(codes.Unimplemented, "method FindOneItem not implemented")
}
func (UnimplementedItemServiceServer) mustEmbedUnimplementedItemServiceServer() {}

// UnsafeItemServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ItemServiceServer will
// result in compilation errors.
type UnsafeItemServiceServer interface {
	mustEmbedUnimplementedItemServiceServer()
}

func RegisterItemServiceServer(s grpc.ServiceRegistrar, srv ItemServiceServer) {
	s.RegisterService(&ItemService_ServiceDesc, srv)
}

func _ItemService_FindOneItem_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ItemServiceServer).FindOneItem(&itemServiceFindOneItemServer{stream})
}

type ItemService_FindOneItemServer interface {
	SendAndClose(*ItemArr) error
	Recv() (*ItemReq, error)
	grpc.ServerStream
}

type itemServiceFindOneItemServer struct {
	grpc.ServerStream
}

func (x *itemServiceFindOneItemServer) SendAndClose(m *ItemArr) error {
	return x.ServerStream.SendMsg(m)
}

func (x *itemServiceFindOneItemServer) Recv() (*ItemReq, error) {
	m := new(ItemReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ItemService_ServiceDesc is the grpc.ServiceDesc for ItemService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ItemService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ItemService",
	HandlerType: (*ItemServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FindOneItem",
			Handler:       _ItemService_FindOneItem_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "src/proto/item/item.proto",
}
